import Estudiante
std1 = Estudiante.Student("n","a","Id","s")
#std1.setname()
#std1.setlastname()
#std1.setid()
std1.setsemester()
print (std1)
materias_std1 = Estudiante.Materias_x_semestre(std1.getsemester())
materias_std1.materias_vistas()
horario_std1 = Estudiante.Horario(materias_std1.get_materias_proximo_semestre())
horario_std1.numero_max_materias()
